#!/usr/bin/env bash
# displays username, user id and home directory for each line of /etc/passwd.

file_path="/etc/passwd"

 

if [ -e "$file_path" ]; then

   

    while IFS=: read -r username _ userid _ _ home_directory _; do

        

        echo "Username: $username"

        echo "User ID: $userid"

        echo "Home Directory: $home_directory"

        echo

    done < "$file_path"

else

    echo "The file $file_path does not exist."

fi
